# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20170927_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
