# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_auto_20170824_2349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItemType',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.Category'),
        ),
    ]
