# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_auto_20170915_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='item_type',
            new_name='categroy',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='item_type',
            new_name='categroy',
        ),
    ]
