# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_auto_20170915_0410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categroy',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='categroy',
            new_name='category',
        ),
    ]
