# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('date_of_visit', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=25)),
                ('message', models.CharField(max_length=750)),
            ],
        ),
    ]
