# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_auto_20170915_0409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='Item',
        ),
    ]
