# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerFeedback',
            new_name='Review',
        ),
    ]
